sound.Add({ name = "Weapon_M249.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/m249/fire.wav"})
sound.Add({ name = "Weapon_M249.BoxOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m249/boxout.wav"})
sound.Add({ name = "Weapon_M249.BoxIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m249/boxin.wav"})
sound.Add({ name = "Weapon_M249.Chain", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m249/chain.wav"})
sound.Add({ name = "Weapon_M249.CoverUp", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m249/coverup.wav"})
sound.Add({ name = "Weapon_M249.CoverDown", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m249/coverdown.wav"})
sound.Add({ name = "Weapon_M249.Pump", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m249/pump.wav"})
sound.Add({ name = "Weapon_M249.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m249/draw.wav"})

sound.Add({ name = "Weapon_Negev.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/negev/fire01.wav", "weapons/negev/fire02.wav"}})
sound.Add({ name = "Weapon_Negev.BoxOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/negev/boxout.wav"})
sound.Add({ name = "Weapon_Negev.BoxIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/negev/boxin.wav"})
sound.Add({ name = "Weapon_Negev.Chain", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/negev/chain.wav"})
sound.Add({ name = "Weapon_Negev.CoverUp", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/negev/coverup.wav"})
sound.Add({ name = "Weapon_Negev.CoverDown", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/negev/coverdown.wav"})
sound.Add({ name = "Weapon_Negev.Pump", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/negev/pump.wav"})

sound.Add({ name = "Weapon_CZ75.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/cz75/fire01.wav", "weapons/cz75/fire02.wav", "weapons/cz75/fire03.wav"}})
sound.Add({ name = "Weapon_CZ75.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/cz75/clipout.wav"})
sound.Add({ name = "Weapon_CZ75.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/cz75/clipin.wav"})
sound.Add({ name = "Weapon_CZ75.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/cz75/slideforward.wav"})
sound.Add({ name = "Weapon_CZ75.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/cz75/slideback.wav"})
sound.Add({ name = "Weapon_CZ75.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/cz75/draw.wav"})

sound.Add({ name = "Weapon_Deagle.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/deagle/fire01.wav", "weapons/deagle/fire02.wav"}})
sound.Add({ name = "Weapon_Deagle.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/clipout.wav"})
sound.Add({ name = "Weapon_Deagle.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/clipin.wav"})
sound.Add({ name = "Weapon_Deagle.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/slideforward.wav"})
sound.Add({ name = "Weapon_Deagle.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/slideback.wav"})
sound.Add({ name = "Weapon_Deagle.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/draw.wav"})
sound.Add({ name = "Weapon_Deagle.Spin01", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin01.wav"})
sound.Add({ name = "Weapon_Deagle.Spin02", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin02.wav"})
sound.Add({ name = "Weapon_Deagle.Spin03", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin03.wav"})
sound.Add({ name = "Weapon_Deagle.Spin04", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin04.wav"})
sound.Add({ name = "Weapon_Deagle.Spin05", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin05.wav"})
sound.Add({ name = "Weapon_Deagle.Spin06", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin06.wav"})
sound.Add({ name = "Weapon_Deagle.Spin07", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin07.wav"})
sound.Add({ name = "Weapon_Deagle.Spin08", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin08.wav"})
sound.Add({ name = "Weapon_Deagle.Spin09", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/deagle/spin09.wav"})

sound.Add({ name = "Weapon_ELITE.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/elite/fire01.wav", "weapons/elite/fire02.wav", "weapons/elite/fire03.wav", "weapons/elite/fire04.wav"}})
sound.Add({ name = "Weapon_ELITE.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/elite/clipout.wav"})
sound.Add({ name = "Weapon_ELITE.LeftClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/elite/leftclipin.wav"})
sound.Add({ name = "Weapon_ELITE.RightClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/elite/rightclipin.wav"})
sound.Add({ name = "Weapon_ELITE.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/elite/slideforward.wav"})
sound.Add({ name = "Weapon_ELITE.Tap", channel = CHAN_STATIC, volume = 0.50, level = SNDLVL_NORM, sound = "weapons/elite/tap.wav"})
sound.Add({ name = "Weapon_ELITE.Draw", channel = CHAN_STATIC, volume = 0.50, level = SNDLVL_NORM, sound = "weapons/elite/draw.wav"})

sound.Add({ name = "Weapon_FiveSeven.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/fiveseven/fire.wav"})
sound.Add({ name = "Weapon_FiveSeven.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/fiveseven/clipout.wav"})
sound.Add({ name = "Weapon_FiveSeven.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/fiveseven/clipin.wav"})
sound.Add({ name = "Weapon_FiveSeven.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/fiveseven/slideforward.wav"})
sound.Add({ name = "Weapon_FiveSeven.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/fiveseven/slideback.wav"})
sound.Add({ name = "Weapon_FiveSeven.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/fiveseven/draw.wav"})

sound.Add({ name = "Weapon_Glock.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"^weapons/glock18/fire01.wav", "^weapons/glock18/fire02.wav"}})
sound.Add({ name = "Weapon_Glock.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/glock18/clipout.wav"})
sound.Add({ name = "Weapon_Glock.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/glock18/clipin.wav"})
sound.Add({ name = "Weapon_Glock.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/glock18/slideforward.wav"})
sound.Add({ name = "Weapon_Glock.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/glock18/slideback.wav"})
sound.Add({ name = "Weapon_Glock.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/glock18/draw.wav"})

sound.Add({ name = "Weapon_P250.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/p250/fire.wav"})
sound.Add({ name = "Weapon_P250.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p250/clipout.wav"})
sound.Add({ name = "Weapon_P250.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p250/clipin.wav"})
sound.Add({ name = "Weapon_P250.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p250/slideforward.wav"})
sound.Add({ name = "Weapon_P250.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p250/slideback.wav"})
sound.Add({ name = "Weapon_P250.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p250/draw.wav"})

sound.Add({ name = "Weapon_P2000.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/p2000/fire01.wav", "weapons/p2000/fire02.wav", "weapons/p2000/fire03.wav"}})
sound.Add({ name = "Weapon_P2000.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p2000/clipout.wav"})
sound.Add({ name = "Weapon_P2000.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p2000/clipin.wav"})
sound.Add({ name = "Weapon_P2000.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p2000/slideforward.wav"})
sound.Add({ name = "Weapon_P2000.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p2000/slideback.wav"})
sound.Add({ name = "Weapon_P2000.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p2000/draw.wav"})

sound.Add({ name = "Weapon_Revolver.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_NORM, sound = "weapons/revolver/fire.wav"})
sound.Add({ name = "Weapon_Revolver.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/revolver/clipout.wav"})
sound.Add({ name = "Weapon_Revolver.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/revolver/clipin.wav"})
sound.Add({ name = "Weapon_Revolver.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/revolver/slideforward.wav"})
sound.Add({ name = "Weapon_Revolver.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/revolver/slideback.wav"})
sound.Add({ name = "Weapon_Revolver.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/revolver/draw.wav"})
sound.Add({ name = "Weapon_Revolver.Prepare", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/revolver/prepare.wav"})
sound.Add({ name = "Weapon_Revolver.Hammer", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/revolver/hammer.wav"})

sound.Add({ name = "Weapon_TEC9.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/tec9/fire.wav"})
sound.Add({ name = "Weapon_TEC9.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/tec9/clipout.wav"})
sound.Add({ name = "Weapon_TEC9.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/tec9/clipin.wav"})
sound.Add({ name = "Weapon_TEC9.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/tec9/boltforward.wav"})
sound.Add({ name = "Weapon_TEC9.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/tec9/boltback.wav"})
sound.Add({ name = "Weapon_TEC9.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/tec9/draw.wav"})

sound.Add({ name = "Weapon_USPS.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/usps/fire01.wav", "weapons/usps/fire02.wav", "weapons/usps/fire03.wav"}})
sound.Add({ name = "Weapon_USPS.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/usps/clipout.wav"})
sound.Add({ name = "Weapon_USPS.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/usps/clipin.wav"})
sound.Add({ name = "Weapon_USPS.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/usps/slideforward.wav"})
sound.Add({ name = "Weapon_USPS.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/usps/slideback.wav"})
sound.Add({ name = "Weapon_USPS.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/usps/draw.wav"})

sound.Add({ name = "Weapon_AK47.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")weapons/ak47/fire.wav"})
sound.Add({ name = "Weapon_AK47.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ak47/clipout.wav"})
sound.Add({ name = "Weapon_AK47.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ak47/clipin.wav"})
sound.Add({ name = "Weapon_AK47.Bolt", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ak47/bolt.wav"})
sound.Add({ name = "Weapon_AK47.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ak47/draw.wav"})

sound.Add({ name = "Weapon_AUG.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/aug/fire01.wav", "weapons/aug/fire02.wav", "weapons/aug/fire03.wav", "weapons/aug/fire04.wav"}})
sound.Add({ name = "Weapon_AUG.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/aug/clipout.wav"})
sound.Add({ name = "Weapon_AUG.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/aug/clipin.wav"})
sound.Add({ name = "Weapon_AUG.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/aug/cliphit.wav"})
sound.Add({ name = "Weapon_AUG.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/aug/boltforward.wav"})
sound.Add({ name = "Weapon_AUG.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/aug/boltback.wav"})
sound.Add({ name = "Weapon_AUG.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/aug/draw.wav"})
sound.Add({ name = "Weapon_AUG.ZoomIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/aug/zoomin.wav"})
sound.Add({ name = "Weapon_AUG.ZoomOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/aug/zoomout.wav"})

sound.Add({ name = "Weapon_FAMAS.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/famas/fire01.wav", "weapons/famas/fire02.wav", "weapons/famas/fire03.wav", "weapons/famas/fire04.wav"}})
sound.Add({ name = "Weapon_FAMAS.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/famas/clipout.wav"})
sound.Add({ name = "Weapon_FAMAS.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/famas/clipin.wav"})
sound.Add({ name = "Weapon_FAMAS.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/famas/cliphit.wav"})
sound.Add({ name = "Weapon_FAMAS.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/famas/boltforward.wav"})
sound.Add({ name = "Weapon_FAMAS.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/famas/boltback.wav"})
sound.Add({ name = "Weapon_FAMAS.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/famas/draw.wav"})

sound.Add({ name = "Weapon_Galil.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/galil/fire01.wav", "weapons/galil/fire02.wav", "weapons/galil/fire03.wav", "weapons/galil/fire04.wav"}})
sound.Add({ name = "Weapon_Galil.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/galil/clipout.wav"})
sound.Add({ name = "Weapon_Galil.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/galil/clipin.wav"})
sound.Add({ name = "Weapon_Galil.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/galil/boltforward.wav"})
sound.Add({ name = "Weapon_Galil.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/galil/boltback.wav"})
sound.Add({ name = "Weapon_Galil.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/galil/draw.wav"})

sound.Add({ name = "Weapon_M4A1S.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/m4a1s/fire.wav"})
sound.Add({ name = "Weapon_M4A1S.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a1s/clipout.wav"})
sound.Add({ name = "Weapon_M4A1S.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a1s/clipin.wav"})
sound.Add({ name = "Weapon_M4A1S.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a1s/cliphit.wav"})
sound.Add({ name = "Weapon_M4A1S.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a1s/boltforward.wav"})
sound.Add({ name = "Weapon_M4A1S.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a1s/boltback.wav"})
sound.Add({ name = "Weapon_M4A1S.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a1s/draw.wav"})

sound.Add({ name = "Weapon_M4A4.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"^weapons/m4a4/fire01.wav", "^weapons/m4a4/fire02.wav", "^weapons/m4a4/fire03.wav", "^weapons/m4a4/fire04.wav"}})
sound.Add({ name = "Weapon_M4A4.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a4/clipout.wav"})
sound.Add({ name = "Weapon_M4A4.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a4/clipin.wav"})
sound.Add({ name = "Weapon_M4A4.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a4/cliphit.wav"})
sound.Add({ name = "Weapon_M4A4.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a4/boltforward.wav"})
sound.Add({ name = "Weapon_M4A4.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a4/boltback.wav"})
sound.Add({ name = "Weapon_M4A4.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a4/draw.wav"})

sound.Add({ name = "Weapon_SG553.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/sg553/fire01.wav", "weapons/sg553/fire02.wav", "weapons/sg553/fire03.wav", "weapons/sg553/fire04.wav"}})
sound.Add({ name = "Weapon_SG553.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sg553/clipout.wav"})
sound.Add({ name = "Weapon_SG553.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sg553/clipin.wav"})
sound.Add({ name = "Weapon_SG553.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sg553/cliphit.wav"})
sound.Add({ name = "Weapon_SG553.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sg553/boltforward.wav"})
sound.Add({ name = "Weapon_SG553.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sg553/boltback.wav"})
sound.Add({ name = "Weapon_SG553.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sg553/draw.wav"})
sound.Add({ name = "Weapon_SG553.ZoomIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sg553/zoomin.wav"})
sound.Add({ name = "Weapon_SG553.ZoomOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sg553/zoomout.wav"})

sound.Add({ name = "Weapon_MAG7.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/mag7/fire01.wav", "weapons/mag7/fire02.wav"}})
sound.Add({ name = "Weapon_MAG7.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mag7/clipout.wav"})
sound.Add({ name = "Weapon_MAG7.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mag7/clipin.wav"})
sound.Add({ name = "Weapon_MAG7.PumpForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mag7/pumpforward.wav"})
sound.Add({ name = "Weapon_MAG7.PumpBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mag7/pumpback.wav"})
sound.Add({ name = "Weapon_MAG7.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mag7/draw.wav"})

sound.Add({ name = "Weapon_Nova.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/nova/fire.wav"})
sound.Add({ name = "Weapon_Nova.InsertShell", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = {"weapons/nova/insertshell01.wav", "weapons/nova/insertshell02.wav", "weapons/nova/insertshell03.wav", "weapons/nova/insertshell04.wav"}})
sound.Add({ name = "Weapon_Nova.Pump", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/nova/pump.wav"})
sound.Add({ name = "Weapon_Nova.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/nova/draw.wav"})

sound.Add({ name = "Weapon_Sawedoff.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/sawedoff/fire.wav"})
sound.Add({ name = "Weapon_Sawedoff.InsertShell", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = {"weapons/sawedoff/insertshell01.wav", "weapons/sawedoff/insertshell02.wav", "weapons/sawedoff/insertshell03.wav"}})
sound.Add({ name = "Weapon_Sawedoff.Pump", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sawedoff/pump.wav"})
sound.Add({ name = "Weapon_Sawedoff.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/sawedoff/draw.wav"})

sound.Add({ name = "Weapon_XM1014.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/xm1014/fire.wav"})
sound.Add({ name = "Weapon_XM1014.InsertShell", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = {"weapons/xm1014/insertshell01.wav", "weapons/xm1014/insertshell02.wav", "weapons/xm1014/insertshell03.wav"}})
sound.Add({ name = "Weapon_XM1014.Pump", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/xm1014/pump.wav"})
sound.Add({ name = "Weapon_XM1014.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/xm1014/draw.wav"})

sound.Add({ name = "Weapon_Bizon.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/bizon/fire01.wav", "weapons/bizon/fire02.wav"}})
sound.Add({ name = "Weapon_Bizon.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/bizon/clipout.wav"})
sound.Add({ name = "Weapon_Bizon.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/bizon/clipin.wav"})
sound.Add({ name = "Weapon_Bizon.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/bizon/boltforward.wav"})
sound.Add({ name = "Weapon_Bizon.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/bizon/boltback.wav"})
sound.Add({ name = "Weapon_Bizon.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/bizon/draw.wav"})

sound.Add({ name = "Weapon_MAC10.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/mac10/fire01.wav", "weapons/mac10/fire02.wav", "weapons/mac10/fire03.wav"}})
sound.Add({ name = "Weapon_MAC10.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mac10/clipout.wav"})
sound.Add({ name = "Weapon_MAC10.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mac10/clipin.wav"})
sound.Add({ name = "Weapon_MAC10.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mac10/boltforward.wav"})
sound.Add({ name = "Weapon_MAC10.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mac10/boltback.wav"})
sound.Add({ name = "Weapon_MAC10.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mac10/draw.wav"})

sound.Add({ name = "Weapon_MP5SD.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/mp5sd/fire.wav"})
sound.Add({ name = "Weapon_MP5SD.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp5sd/clipout.wav"})
sound.Add({ name = "Weapon_MP5SD.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp5sd/clipin.wav"})
sound.Add({ name = "Weapon_MP5SD.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp5sd/boltforward.wav"})
sound.Add({ name = "Weapon_MP5SD.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp5sd/boltback.wav"})
sound.Add({ name = "Weapon_MP5SD.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp5sd/draw.wav"})

sound.Add({ name = "Weapon_MP7.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {")weapons/mp7/fire01.wav", ")weapons/mp7/fire02.wav", ")weapons/mp7/fire03.wav", ")weapons/mp7/fire04.wav"}})
sound.Add({ name = "Weapon_MP7.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp7/clipout.wav"})
sound.Add({ name = "Weapon_MP7.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp7/clipin.wav"})
sound.Add({ name = "Weapon_MP7.SlideForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp7/slideforward.wav"})
sound.Add({ name = "Weapon_MP7.SlideBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp7/slideback.wav"})
sound.Add({ name = "Weapon_MP7.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp7/draw.wav"})

sound.Add({ name = "Weapon_MP9.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/mp9/fire01.wav", "weapons/mp9/fire02.wav", "weapons/mp9/fire03.wav", "weapons/mp9/fire04.wav"}})
sound.Add({ name = "Weapon_MP9.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp9/clipout.wav"})
sound.Add({ name = "Weapon_MP9.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp9/clipin.wav"})
sound.Add({ name = "Weapon_MP9.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp9/boltforward.wav"})
sound.Add({ name = "Weapon_MP9.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp9/boltback.wav"})
sound.Add({ name = "Weapon_MP9.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/mp9/draw.wav"})

sound.Add({ name = "Weapon_P90.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/p90/fire01.wav", "weapons/p90/fire02.wav", "weapons/p90/fire03.wav"}})
sound.Add({ name = "Weapon_P90.ClipRelease", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p90/cliprelease.wav"})
sound.Add({ name = "Weapon_P90.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p90/clipout.wav"})
sound.Add({ name = "Weapon_P90.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p90/clipin.wav"})
sound.Add({ name = "Weapon_P90.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p90/cliphit.wav"})
sound.Add({ name = "Weapon_P90.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p90/boltforward.wav"})
sound.Add({ name = "Weapon_P90.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p90/boltback.wav"})
sound.Add({ name = "Weapon_P90.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/p90/draw.wav"})

sound.Add({ name = "Weapon_UMP45.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/ump45/fire01.wav", "weapons/ump45/fire02.wav"}})
sound.Add({ name = "Weapon_UMP45.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ump45/clipout.wav"})
sound.Add({ name = "Weapon_UMP45.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ump45/clipin.wav"})
sound.Add({ name = "Weapon_UMP45.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ump45/boltforward.wav"})
sound.Add({ name = "Weapon_UMP45.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ump45/boltback.wav"})
sound.Add({ name = "Weapon_UMP45.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ump45/draw.wav"})

sound.Add({ name = "Weapon_AWP.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/awp/fire01.wav", "weapons/awp/fire02.wav"}})
sound.Add({ name = "Weapon_AWP.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/awp/clipout.wav"})
sound.Add({ name = "Weapon_AWP.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/awp/clipin.wav"})
sound.Add({ name = "Weapon_AWP.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/awp/cliphit.wav"})
sound.Add({ name = "Weapon_AWP.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/awp/boltforward.wav"})
sound.Add({ name = "Weapon_AWP.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/awp/boltback.wav"})
sound.Add({ name = "Weapon_AWP.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/awp/draw.wav"})
sound.Add({ name = "Weapon_AWP.Zoom", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/awp/zoom.wav"})

sound.Add({ name = "Weapon_G3SG1.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/g3sg1/fire01.wav", "weapons/g3sg1/fire02.wav", "weapons/g3sg1/fire03.wav"}})
sound.Add({ name = "Weapon_G3SG1.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/g3sg1/clipout.wav"})
sound.Add({ name = "Weapon_G3SG1.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/g3sg1/clipin.wav"})
sound.Add({ name = "Weapon_G3SG1.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/g3sg1/boltforward.wav"})
sound.Add({ name = "Weapon_G3SG1.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/g3sg1/boltback.wav"})
sound.Add({ name = "Weapon_G3SG1.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/g3sg1/draw.wav"})
sound.Add({ name = "Weapon_G3SG1.Zoom", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/g3sg1/zoom.wav"})

sound.Add({ name = "Weapon_SCAR20.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = {"weapons/scar20/fire01.wav", "weapons/scar20/fire02.wav", "weapons/scar20/fire03.wav"}})
sound.Add({ name = "Weapon_SCAR20.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/scar20/clipout.wav"})
sound.Add({ name = "Weapon_SCAR20.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/scar20/clipin.wav"})
sound.Add({ name = "Weapon_SCAR20.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/scar20/cliphit.wav"})
sound.Add({ name = "Weapon_SCAR20.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/scar20/boltforward.wav"})
sound.Add({ name = "Weapon_SCAR20.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/scar20/boltback.wav"})
sound.Add({ name = "Weapon_SCAR20.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/scar20/draw.wav"})
sound.Add({ name = "Weapon_SCAR20.Zoom", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/scar20/zoom.wav"})

sound.Add({ name = "Weapon_SSG08.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "weapons/ssg08/fire.wav"})
sound.Add({ name = "Weapon_SSG08.ClipOut", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ssg08/clipout.wav"})
sound.Add({ name = "Weapon_SSG08.ClipIn", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ssg08/clipin.wav"})
sound.Add({ name = "Weapon_SSG08.ClipHit", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ssg08/cliphit.wav"})
sound.Add({ name = "Weapon_SSG08.BoltForward", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ssg08/boltforward.wav"})
sound.Add({ name = "Weapon_SSG08.BoltBack", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ssg08/boltback.wav"})
sound.Add({ name = "Weapon_SSG08.Draw", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ssg08/draw.wav"})
sound.Add({ name = "Weapon_SSG08.Zoom", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/ssg08/zoom.wav"})

-- TFA

sound.Add({ name = "TFA_INS2.M9.1", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = {")weapons/tfa_ins2/m9/fire_1.wav", ")weapons/tfa_ins2/m9/fire_2.wav", ")weapons/tfa_ins2/m9/fire_3.wav"}})
sound.Add({ name = "TFA_INS2.M9.2", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")weapons/tfa_ins2/m9/fire_sil.wav"})
sound.Add({ name = "TFA_INS2.M9.Boltback", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/m9/handling/m9_boltback.wav"})
sound.Add({ name = "TFA_INS2.M9.Boltrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/m9/handling/m9_boltrelease.wav"})
sound.Add({ name = "TFA_INS2.M9.Empty", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/m9/handling/m9_empty.wav"})
sound.Add({ name = "TFA_INS2.M9.Magrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/m9/handling/m9_magrelease.wav"})
sound.Add({ name = "TFA_INS2.M9.Magout", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/m9/handling/m9_magout.wav"})
sound.Add({ name = "TFA_INS2.M9.Magin", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/m9/handling/m9_magin.wav"})
sound.Add({ name = "TFA_INS2.M9.MagHit", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/m9/handling/m9_maghit.wav"})

sound.Add({ name = "TFA_INS2.USP_M.1", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")/weapons/tfa_ins2/usp_match/usp_unsil-1.wav"})
sound.Add({ name = "TFA_INS2.USP_M.2", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")/weapons/tfa_ins2/usp_match/usp1.wav"})
sound.Add({ name = "TFA_INS2.USP_M.Empty", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")/weapons/tfa_ins2/usp_match/usp_match_empty.wav"})
sound.Add({ name = "TFA_INS2.USP_M.Boltback", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")/weapons/tfa_ins2/usp_match/usp_match_boltback.wav"})
sound.Add({ name = "TFA_INS2.USP_M.Boltrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")/weapons/tfa_ins2/usp_match/usp_match_boltrelease.wav"})
sound.Add({ name = "TFA_INS2.USP_M.Magrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")/weapons/tfa_ins2/usp_match/usp_match_magrelease.wav"})
sound.Add({ name = "TFA_INS2.USP_M.Magout", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")/weapons/tfa_ins2/usp_match/usp_match_magout.wav"})
sound.Add({ name = "TFA_INS2.USP_M.Magin", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")/weapons/tfa_ins2/usp_match/usp_match_magin.wav"})
sound.Add({ name = "TFA_INS2.USP_M.MagHit", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")/weapons/tfa_ins2/usp_match/usp_match_maghit.wav"})

sound.Add({ name = "Weapon_IMIUZI_TFA_N_1", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")weapons/tfa_ins2_imi_uzi/uzi_fire.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.Hit", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/m4a1_maghitrelease.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.Boltback", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/aks_boltback.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.MagoutRattle", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/aks_magout_rattle.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.Empty", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/kar98_empty.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.Magrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/m1carbine_para_magrelease.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.Magout", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/mp40_magout.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.Magin", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/mp40_magin.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.Boltlock", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/mp40_boltlock.wav"})
sound.Add({ name = "Weapon_IMIUZI_TFA_N.Boltunlock", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2_imi_uzi/mp40_boltunlock.wav"})

sound.Add({ name = "TFA_INS2_MINIMI.1", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")weapons/tfa_ins2/minimi/m249_fp.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.2", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")weapons/tfa_ins2/minimi/m249_suppressed_fp.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.Empty", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_empty.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.CoverOpen", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_coveropen.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.CoverClose", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_coverclose.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.FetchMag", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_fetchmag.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.ThrowAway", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_beltremove.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.Magout", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_magout.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.MagoutFull", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_magout.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.MagHit", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_maghit.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.MagIn", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_magin.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.BeltJingle", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_bulletjingle.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.BeltAlign", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_beltalign.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.ArmMovement_01", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_armmovement_01.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.ArmMovement_02", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_armmovement_02.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.Boltback", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_boltback.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.Boltrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_boltrelease.wav"})
sound.Add({ name = "TFA_INS2_MINIMI.Shoulder", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/minimi/m249_shoulder.wav"})

sound.Add({ name = "TFA_INS2_AKZ.1", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")weapons/tfa_ins2/akz/ak47_fp.wav"})
sound.Add({ name = "TFA_INS2_AKZ.2", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")weapons/tfa_ins2/akz/ak47_suppressed_fp.wav"})
sound.Add({ name = "TFA_INS2_AKZ.Empty", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/akz/ak47_empty.wav"})
sound.Add({ name = "TFA_INS2_AKZ.ROF", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = {")weapons/tfa_ins2/akz/ak47_fireselect_1.wav", ")weapons/tfa_ins2/akz/ak47_fireselect_2.wav"}})
sound.Add({ name = "TFA_INS2_AKZ.MagRelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/akz/ak47_magrelease.wav"})
sound.Add({ name = "TFA_INS2_AKZ.Magout", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/akz/ak47_magout.wav"})
sound.Add({ name = "TFA_INS2_AKZ.Rattle", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/akz/ak47_rattle.wav"})
sound.Add({ name = "TFA_INS2_AKZ.Magin", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/akz/ak47_magin.wav"})
sound.Add({ name = "TFA_INS2_AKZ.Boltback", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/akz/ak47_boltback.wav"})
sound.Add({ name = "TFA_INS2_AKZ.Boltrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = ")weapons/tfa_ins2/akz/ak47_boltrelease.wav"})

sound.Add({ name = "Weapon_Garand.1", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, sound = ")weapons/m1garand/garand_fp.wav"})
sound.Add({ name = "Weapon_Garand.Ping", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = {"weapons/m1garand/handling/garand_ping_01.wav", "weapons/m1garand/handling/garand_ping_02.wav", "weapons/m1garand/handling/garand_ping_03.wav", "weapons/m1garand/handling/garand_ping_04.wav", "weapons/m1garand/handling/garand_ping_05.wav"}})
sound.Add({ name = "Weapon_Garand.Magrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/m1garand/handling/garand_magrelease.wav"})
sound.Add({ name = "Weapon_Garand.Boltback", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/m1garand/handling/garand_boltback.wav"})
sound.Add({ name = "Weapon_Garand.Magout", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/m1garand/handling/garand_magout.wav"})
sound.Add({ name = "Weapon_Garand.MagFetch", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/m1garand/handling/garand_fetchmag.wav"})
sound.Add({ name = "Weapon_Garand.Magin", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/m1garand/handling/garand_magin.wav"})
sound.Add({ name = "Weapon_Garand.MagHit", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/m1garand/handling/garand_maghit.wav"})
sound.Add({ name = "Weapon_Garand.Boltrelease", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/m1garand/handling/garand_boltrelease.wav"})
sound.Add({ name = "Weapon_Garand.Rattle", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/m1garand/handling/garand_rattle.wav"})

sound.Add({ name = "robotnik_bo1_law.latch", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/robotnik_bo1_law/latch.wav"})
sound.Add({ name = "robotnik_bo1_law.slide", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/robotnik_bo1_law/slide.wav"})
sound.Add({ name = "robotnik_bo1_law.deploy", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/robotnik_bo1_law/deploy.wav"})
sound.Add({ name = "robotnik_bo1_law.cloth", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/robotnik_bo1_law/cloth.wav"})

sound.Add({ name = "TFA_INS2.PistolDraw", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = {")weapons/ins2/uni/uni_pistol_draw_01.wav", ")weapons/ins2/uni/uni_pistol_draw_02.wav", ")weapons/ins2/uni/uni_pistol_draw_03.wav"}})
sound.Add({ name = "TFA_INS2.Draw", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = {")weapons/ins2/uni/uni_weapon_draw_01.wav", ")weapons/ins2/uni/uni_weapon_draw_02.wav", ")weapons/ins2/uni/uni_weapon_draw_03.wav"}})
sound.Add({ name = "Universal.Draw", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "weapons/universal/uni_weapon_draw.wav"})

-- ArcCW

sound.Add({ name = "ArcCW_BO1.M203_Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw/bo1_m203/40mm_fire.wav"})
sound.Add({ name = "ArcCW_BO2.Chicom_Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw/bo2_generic_smg/fire_chicom.wav"})
sound.Add({ name = "ArcCW_BO2.EVO3_Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw/bo2_generic_smg/fire_evo3.wav"})
sound.Add({ name = "ArcCW_BO2.MTAR_Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw/bo2_generic_ar/fire_mtar.wav"})
sound.Add({ name = "ArcCW_BO2.PDW57_Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw/bo2_generic_smg/fire_pdw.wav"})
sound.Add({ name = "ArcCW_BO2.QBB_Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw/bo2_generic_lmg/fire_qbb.wav"})
sound.Add({ name = "ArcCW_BO2.SMR_Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")weapons/arccw/bo2_generic_ar/fire_smr.wav"})
sound.Add({ name = "ArcCW_BO2.MP7_Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw/bo2_generic_smg/fire_mp7.wav"})

sound.Add({ name = "ArcCW_BO1.Kiparis_Bolt", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_kiparis/charge.wav"})
sound.Add({ name = "ArcCW_BO1.Kiparis_MagIn", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_kiparis/in.wav"})
sound.Add({ name = "ArcCW_BO1.Kiparis_MagOut", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_kiparis/out.wav"})
sound.Add({ name = "ArcCW_BO1.M14_Tap", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_m14/tap.wav"})
sound.Add({ name = "ArcCW_BO1.M16_Button", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_m16/m16_button.wav"})
sound.Add({ name = "ArcCW_BO1.M16_Futz", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_m16/m16_futz.wav"})
sound.Add({ name = "ArcCW_BO1.M16_MagIn", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_m16/m16_mag_in.wav"})
sound.Add({ name = "ArcCW_BO1.M16_MagOut", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_m16/m16_mag_out.wav"})
sound.Add({ name = "ArcCW_BO1.MK_Back", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_generic_shotgun/pump_back.wav"})
sound.Add({ name = "ArcCW_BO1.MK_Fwd", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_generic_shotgun/pump_fwd.wav"})
sound.Add({ name = "ArcCW_BO1.MK_Shell", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = {"^weapons/arccw/bo1_generic_shotgun/shell1.wav", "^weapons/arccw/bo1_generic_shotgun/shell2.wav", "^weapons/arccw/bo1_generic_shotgun/shell3.wav", "^weapons/arccw/bo1_generic_shotgun/shell4.wav", "^weapons/arccw/bo1_generic_shotgun/shell5.wav", "^weapons/arccw/bo1_generic_shotgun/shell6.wav"}})
sound.Add({ name = "ArcCW_BO1.RPK_Futz", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_rpk/futz.wav"})
sound.Add({ name = "ArcCW_BO1.RPK_MagIn", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_rpk/in.wav"})
sound.Add({ name = "ArcCW_BO1.RPK_MagOut", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo1_rpk/out.wav"})
sound.Add({ name = "ArcCW_BO2.AR_Back", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_ar/back.wav"})
sound.Add({ name = "ArcCW_BO2.AR_Charge", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_ar/charge.wav"})
sound.Add({ name = "ArcCW_BO2.AR_Fwd", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_ar/fwd.wav"})
sound.Add({ name = "ArcCW_BO2.AR_MagIn", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_ar/in.wav"})
sound.Add({ name = "ArcCW_BO2.AR_MagOut", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_ar/out.wav"})
sound.Add({ name = "ArcCW_BO2.LMG_Back", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_lmg/back.wav"})
sound.Add({ name = "ArcCW_BO2.LMG_Fwd", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_lmg/fwd.wav"})
sound.Add({ name = "ArcCW_BO2.MP7_Charge", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_smg/charge_mp7.wav"})
sound.Add({ name = "ArcCW_BO2.MP7_In", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_smg/in_mp7.wav"})
sound.Add({ name = "ArcCW_BO2.MP7_Out", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw/bo2_generic_smg/out_mp7.wav"})

-- UD stuff

sound.Add({ name = "UD.Common.Rottle", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = {"^/arccw_uc/common/cloth_1.ogg", "^/arccw_uc/common/cloth_2.ogg", "^/arccw_uc/common/cloth_3.ogg", "^/arccw_uc/common/cloth_4.ogg", "^/arccw_uc/common/cloth_6.ogg", "^/arccw_uc/common/rattle.ogg"}})
sound.Add({ name = "UD.Common.Raise", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^/arccw_uc/common/raise.ogg"})
sound.Add({ name = "UD.Common.Shoulder", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^/arccw_uc/common/shoulder.ogg"})
sound.Add({ name = "UD.Common.Grab", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^/arccw_uc/common/grab.ogg"})
sound.Add({ name = "UD.Common.Cloth4", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^/arccw_uc/common/cloth_4.ogg"})
sound.Add({ name = "UD.Common.Rifle_Magdrop", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^/arccw_uc/common/rifle_magdrop.ogg"})

sound.Add({ name = "UD.M16.Fire", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw_ud/m16/first.ogg"})
sound.Add({ name = "UD.M16.Fire_Sup", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw_ud/m16/fire_supp.ogg"})
sound.Add({ name = "UD.M16.Fire_Beowulf", channel = CHAN_WEAPON, volume = 0.9, level = SNDLVL_GUNFIRE, pitch = {95, 105}, sound = ")^weapons/arccw_ud/m16/fire_usas.ogg"})

sound.Add({ name = "UD.M16.Rattle", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = {"^weapons/arccw_ud/m16/rattle_1.ogg", "^weapons/arccw_ud/m16/rattle_2.ogg", "^weapons/arccw_ud/m16/rattle_3.ogg"}})
sound.Add({ name = "UD.M16.Rattle3", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw_ud/m16/rattle_3.ogg"})
sound.Add({ name = "UD.M16.Magout", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw_ud/m16/magout.ogg"})
sound.Add({ name = "UD.M16.Magin", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw_ud/m16/magin.ogg"})
sound.Add({ name = "UD.M16.Magtap", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw_ud/m16/magtap.ogg"})
sound.Add({ name = "UD.M16.Boltdrop", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw_ud/m16/boltdrop.ogg"})
sound.Add({ name = "UD.M16.Chback", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw_ud/m16/chback.ogg"})
sound.Add({ name = "UD.M16.Chamber", channel = CHAN_STATIC, volume = 0.7, level = SNDLVL_NORM, sound = "^weapons/arccw_ud/m16/chamber.ogg"})

-- Custom stuff

sound.Add({ name = "Terminator_SMG.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_smg.wav"})
sound.Add({ name = "Terminator_1911.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_1911.wav"})
sound.Add({ name = "Terminator_Tar.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_tar.wav"})
sound.Add({ name = "Terminator_SilencedThwack.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_silencedthwack.wav"})
sound.Add({ name = "Terminator_M24.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_m24.wav"})
sound.Add({ name = "Terminator_Sniper.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_sniper.wav"})
sound.Add({ name = "Terminator_SBR.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_sbr.wav"})
sound.Add({ name = "Terminator_SilencedSnap.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_silencedsnap.wav"})
sound.Add({ name = "Terminator_Shotgun.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_shotgun.wav"})
sound.Add({ name = "Terminator_Shotgun2.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_shotgun2.wav"})
sound.Add({ name = "Terminator_USP.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_usp.wav"})
sound.Add({ name = "Terminator_Sharp.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_sharp.wav"})
sound.Add({ name = "Terminator_PistolCrack.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_pistolcrack.wav"})
sound.Add({ name = "Terminator_Famas.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_famas.wav"})
sound.Add({ name = "Terminator_M1.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_m1.wav"})
sound.Add({ name = "Terminator_M203.Smoke", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_m203_smoke.wav"})
sound.Add({ name = "Terminator_Mortar.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_mortar.wav"})
sound.Add({ name = "Terminator_AK47.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")weapons/ak47/fire.wav"})
sound.Add({ name = "Terminator_RPG.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_rpg.wav"})
sound.Add({ name = "Terminator_SilencedSocom.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = ")tekka/weapons/weapon_silencedsocom.wav"})
sound.Add({ name = "Terminator_Thud.Fire", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, sound = "^tekka/weapons/weapon_thud.wav"})

sound.Add({ name = "Terminator_Minigun.Socom", channel = CHAN_WEAPON, volume = 0.40, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_socom.wav"})
sound.Add({ name = "Terminator_Minigun.ThudSoft", channel = CHAN_WEAPON, volume = 0.40, level = SNDLVL_GUNFIRE, sound = ")^tekka/weapons/weapon_thudsoft.wav"})
sound.Add({ name = "Terminator_Minigun.Blat", channel = CHAN_WEAPON, volume = 0.40, level = SNDLVL_GUNFIRE, pitch = {92, 112}, sound = ")tekka/weapons/weapon_blat.wav"})
sound.Add({ name = "Terminator_Minigun.Chaingun", channel = CHAN_WEAPON, volume = 0.40, level = SNDLVL_GUNFIRE, pitch = {92, 112}, sound = ")tekka/weapons/weapon_chaingun.wav"})

sound.Add({ name = "Terminator_Minigun.T410", channel = CHAN_WEAPON, volume = 0.40, level = SNDLVL_GUNFIRE, pitch = {92, 112}, sound = ")tekka/weapons/weapon_gut.wav"})

sound.Add({ name = "Terminator_Plasma.T100", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = ")tekka/weapons/plasma_single11.wav"})
sound.Add({ name = "Terminator_Plasma.T500", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = ")tekka/weapons/weapon_laser_smg.wav"})

sound.Add({ name = "Terminator_Plasma.SkyNET.30watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = "^tekka/weapons/plasma_single3.wav"})
sound.Add({ name = "Terminator_Plasma.SkyNET.40watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {80, 90}, sound = "^tekka/weapons/plasma_single7.wav"})
sound.Add({ name = "Terminator_Plasma.SkyNET.45watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = ")tekka/weapons/plasma_single3.wav"})
sound.Add({ name = "Terminator_Plasma.SkyNET.50watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = "^tekka/weapons/plasma_single10.wav"})
sound.Add({ name = "Terminator_Plasma.SkyNET.55watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE,
	pitch = {90, 110}, sound = "^tekka/weapons/plasma_single7.wav"})
sound.Add({ name = "Terminator_Plasma.SkyNET.60watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {100, 110}, sound = "^tekka/weapons/plasma_single4.wav"})
sound.Add({ name = "Terminator_Plasma.SkyNET.70watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 100}, sound = ")tekka/weapons/plasma_rifle4.wav"})

sound.Add({ name = "Terminator_Plasma.JuryRigged.Sten", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = "^tekka/weapons/plasma_rifle1.wav"})
sound.Add({ name = "Terminator_Plasma.JuryRigged.M4", channel = CHAN_WEAPON, volume = 0.40, level = SNDLVL_GUNFIRE, pitch = {110, 130}, sound = "^tekka/weapons/plasma_rifle1.wav"})
sound.Add({ name = "Terminator_Plasma.JuryRigged.M249", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = "^tekka/weapons/weapon_magnetic.wav"})

sound.Add({ name = "Terminator_Plasma.TC.20watt", channel = CHAN_WEAPON, volume = 0.30, level = SNDLVL_GUNFIRE, pitch = {120, 140}, sound = "^tekka/weapons/plasma_pistol.wav"})
sound.Add({ name = "Terminator_Plasma.TC.30watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {80, 100}, sound = "^tekka/weapons/plasma_single3.wav"})
sound.Add({ name = "Terminator_Plasma.TC.40watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {100, 120}, sound = "^tekka/weapons/plasma_single11.wav"})
sound.Add({ name = "Terminator_Plasma.TC.45watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {120, 140}, sound = ")tekka/weapons/weapon_laser_smg.wav"})
sound.Add({ name = "Terminator_Plasma.TC.50watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = "^tekka/weapons/plasma_single4.wav"})

sound.Add({ name = "Terminator_Plasma.Sentinel.35watt", channel = CHAN_WEAPON, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {120, 140}, sound = ")tekka/weapons/weapon_laser_smg.wav"})

sound.Add({ name = "Terminator_Weapon.Movement", channel = CHAN_STATIC, volume = 0.20, level = SNDLVL_NORM, sound = {"weapons/movement01.wav", "weapons/movement02.wav", "weapons/movement03.wav"}})
sound.Add({ name = "Terminator_Weapon.Jam", channel = CHAN_STATIC, volume = 0.90, level = SNDLVL_NORM, sound = "weapons/lowammo.wav"})
sound.Add({ name = "Terminator_Weapon.Empty", channel = CHAN_STATIC, volume = 0.90, level = SNDLVL_NORM, sound = "weapons/clipempty_rifle.wav"})

sound.Add({ name = "Terminator_Turret.Primary", channel = CHAN_STATIC, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {92, 112}, sound = ")weapons/machinegun_lvl2.ogg"})
sound.Add({ name = "Terminator_Turret.Secondary", channel = CHAN_STATIC, volume = 0.90, level = SNDLVL_GUNFIRE, pitch = {90, 110}, sound = ")tekka/weapons/plasma_clank.wav"})

-- Fixes for Dave's guns

sound.Add({ name = "Weapon_M4A1.Boltrelease", channel = CHAN_STATIC, volume = 0.70, level = SNDLVL_NORM, sound = "weapons/m4a1/m4a1_boltpull.wav"})

sound.Add({ name = "Food.Drink", channel = CHAN_STATIC, volume = 0.8, level = SNDLVL_60dB, sound = {"needs/drink1.wav", "needs/drink2.wav", "needs/drink3.wav"}})
sound.Add({ name = "Food.Eat", channel = CHAN_STATIC, volume = 0.8, level = SNDLVL_60dB, sound = {"needs/eatsitting1.wav", "needs/eatsitting2.wav", "needs/eatsitting3.wav"}})
sound.Add({ name = "Food.Snack", channel = CHAN_STATIC, volume = 0.8, level = SNDLVL_60dB, sound = {"needs/choceat1.wav", "needs/choceat2.wav", "needs/choceat3.wav"}})

sound.Add({ name = "fart", channel = CHAN_AUTO, volume = 1, level = 75, pitch = {90, 110}, sound = "fart.wav"})
